version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Switching to project directory..."
      - cd devops-vite-project

      - echo "Installing Node.js dependencies..."
      - npm ci

      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - sudo mv ./bin/trivy /usr/local/bin/trivy


      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

      - echo "Installing dependencies..."
      - echo "Installing jq..."
      - yum install -y jq
      - echo "Dependencies installed."

  pre_build:
    commands:
      - echo "Fetching Docker credentials from AWS Secrets Manager..."
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query 'SecretString' --output text | jq -r .DOCKER_USERNAME)
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query 'SecretString' --output text | jq -r .DOCKER_PASSWORD)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo "Building Vite app..."
      - npm run build

      - echo "Building Docker image..."
      - docker build -t vite-app-image .

  post_build:
    commands:
      - |
        if docker images | grep -q vite-app-image; then
          echo "Scanning Docker image with Trivy..."
          trivy image vite-app-image --exit-code 1 --severity CRITICAL,HIGH
        else
          echo "Skipping Trivy scan as image build failed."
        fi

artifacts:
  files:
    - '**/*'
  base-directory: devops-vite-project/dist
