version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo Installing Trivy...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - sudo mv trivy /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to Docker...
      - docker --version
      - echo Starting build process...

  build:
    commands:
      - echo Building Vite app...
      - npm run build
      - echo Building Docker image...
      - docker build -t vite-app-image ./devops-vite-project

  post_build:
    commands:
      - echo Scanning Docker image with Trivy...
      - trivy image vite-app-image --exit-code 0 --severity HIGH,CRITICAL
      - echo Build and scan completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: devops-vite-project/dist
