version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Switching to project directory..."
      - cd devops-vite-project

      - echo "Installing Node.js dependencies..."
      - npm ci

      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - sudo mv ./bin/trivy /usr/local/bin/trivy


      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "Docker version:"
      - docker --version

  build:
    commands:
      - echo "Building Vite app..."
      - npm run build

      - echo "Building Docker image..."
      - docker build -t vite-app-image .

  post_build:
    commands:
      - echo "Scanning Docker image with Trivy..."
      - trivy image vite-app-image --exit-code 1 --severity CRITICAL,HIGH

      - echo "Build and security scan completed at $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: devops-vite-project/dist
