---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
  annotations:
    # sealedsecrets.bitnami.com/trigger: "recreate-1"
    sealedsecrets.bitnami.com/trigger: "recreate-$(date +%s)"
spec:
  encryptedData:
    .dockerconfigjson: AgBqhPysXX5Mthaqur7KFg4kW4v7c/1UyVrUGNl7OkI6ZHP98clko/0kC1LOYQ54nWQGEAQQiNEMokY+e9YyA+0fhMKBfTPJ/DpsWzKUDe6EC/SKMc9Jx2lGK/HkLHn8FUX60tacyYOL7mPw9dKbRma3cCyGExfmxePpX0HEob7GavCGtVpnZLSCESWs4e95v5BLzsqEg7EJiLBlSS5Dpogw3b7dcDBjlVDYg2AMnmCp7LuWFunODxH0kS1vkRJ8MnIUhju+bx0ODnSjnH1ZBzUXWB3ypV977JBQyCkDC7S3O9tDVyDeBBsZCJFiFYOcrnHFuJnvq96BFPHBn+7oUDBHSviUuhbGw75r283vsQHckbDPQQ9dUYgD77JOj/LCeWsaQmrcNW9Cn0+lRakERJU8H2JI5ITIIZajiDjePrDxrOdiM9yKKF5YK6Ei7CX0rIy2XE023tivSpS1hg2dj5WllNopNrFKgJVcez8rnrisu2kSRDcrhlYn3H5umWPPmjZiEnfZzgKentQwG2WH/Y/B8EVqShiczI/PpSypvHzldk+I56Lr5bWfB5czGsry5JuTSQCdLjjNNTTTdMkzfrpCfcRSZSJSZGo9biv6n/2O7kPbZUt47lPgQ7NHrh2CGzMPt0OsDdiy1BjPU5LMhAK9NYB4U/SM/ts5YAnpWLov1h4ea4t+TE8n9AgDSlIHJIBwic/Tb7dGqq1/Roc0T8XmBmVRSvwpm0nX/S7vCYldJQTuRtu685fJnGuTQKrxIguv3I378eU5yE9o616wG5k0ENBT0XjKbWTBpv2GT79d0DFGva4ZfeaUrvTyX4FkfBQ6k0LyDdFlLmFgbu0fK2klfrQdZzsHXItGnvN7fiaDNSpuwfkDztdGxt+Q3mDtzAWeYaPuNNzrSUUTExMz8f+kJ7d+LaRmUustY1Fdk6kBwxojmzm5bpB1tKS6eypQrcfyW4kLorQD9/Kwmr3sBQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
