apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: vite-app
  ports:
    - port: 80
      targetPort: 5173  # the port your app listens on inside the container
      nodePort: 30007   # a high-numbered port in range 30000–32767
